import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import HomeProduct from '../components/HomeProduct'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/8/84/Apple_Computer_Logo_rainbow.svg" />
      </Head>
      <main className='grey-background' >
        <Nav />
        <HomeProduct />
      </main>
    </div>
  )
}
